quarkus.langchain4j.pgvector.dimension=1536
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-2024-08-06
quarkus.http.limits.max-body-size=1G
#quarkus.langchain4j.chat-memory.memory-window.max-messages=20
# Path to the directory where the documents are stored
quarkus.langchain4j.easy-rag.path=/home/bburke/projects/pearls

# optional properties that control how
# the documents are split into segments
quarkus.langchain4j.easy-rag.max-segment-size=100
quarkus.langchain4j.easy-rag.max-overlap-size=25
quarkus.langchain4j.easy-rag.max-results=4

