quarkus.langchain4j.pgvector.dimension=1536
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-2024-08-06
quarkus.http.limits.max-body-size=1G
#quarkus.langchain4j.chat-memory.memory-window.max-messages=20

